# Generated by Django 5.0.1 on 2024-06-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfaWebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('thumbnail', models.ImageField(upload_to='BibleBook_Playlist/')),
            ],
        ),
    ]
