# Generated by Django 5.0.1 on 2024-06-26 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bfaWebApp', '0002_biblebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sermon',
            name='bible_books',
        ),
    ]
