# Generated by Django 5.0.1 on 2024-06-26 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfaWebApp', '0003_remove_sermon_bible_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='bibleBook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sermons', to='bfaWebApp.biblebook'),
        ),
    ]
