# Generated by Django 5.0.1 on 2024-06-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfaWebApp', '0004_sermon_biblebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='isExpository',
            field=models.BooleanField(default=False),
        ),
    ]
