# Generated by Django 5.0.1 on 2024-06-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfaWebApp', '0005_sermon_isexpository'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblebook',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
