# Generated by Django 5.0.1 on 2024-06-29 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bfaWebApp', '0006_biblebook_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sermon',
            name='bibleBook',
        ),
        migrations.RemoveField(
            model_name='sermon',
            name='sermon_category',
        ),
        migrations.DeleteModel(
            name='VideoDownload',
        ),
        migrations.DeleteModel(
            name='BibleBook',
        ),
        migrations.DeleteModel(
            name='Sermon',
        ),
        migrations.DeleteModel(
            name='Sermon_Category',
        ),
    ]
