# Generated by Django 5.0.1 on 2024-06-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfaSermons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='thumbnail',
            field=models.ImageField(upload_to='sermon_thumbnails/'),
        ),
    ]
