from django.urls import path
from bfaWebApp.views import *
from bfaWebApp import views 

urlpatterns = [
    path("", views.index, name="index"),
    path("blog", BlogPostListView.as_view()),
    path("blog-tags", TagsListView.as_view()),
    path("blog-search", BlogPostListView.as_view(), name="blog-search"),
    path("recent", BlogPostListView.as_view()),
    path("popular", BlogPost_PopularListView.as_view()),
    path("trending", BlogPost_TrendingListView.as_view()),
    path("editorsPick", BlogPost_EditorsPickListView.as_view()),
    path("blog-details/<slug>", BlogPostDetailsView.as_view()),
    path('comments', views.CommentCreateView.as_view(), name='comment-create'),
    path('replies', views.ReplyCreateView.as_view(), name='reply-create'),
    path("blog-author", AuthorListView.as_view()),
    path("blog-author-details/<name>", AuthorDetailsView.as_view()), 
    path("blog-category", CategoryListView.as_view()),
    path("blog-category-details/<title>", CategoryDetailsView.as_view()),
    path("sermons", SermonListView.as_view()),
    path("sermon-details/<slug>", SermonDetailsView.as_view()),
    path("bible-book", BibleBookListView.as_view()),
    path("bible-book-details/<slug>", BibleBookDetailsView.as_view()),
    path("biographical-sermons", BiographicalSermonsView.as_view()),
    path("doctrinal-sermons", DoctrinalSermonsView.as_view()),
    path("practical-sermons", PracticalSermonsView.as_view()),
    path("expository-sermons", ExpositorySermonsView.as_view()),
    path("expository-sermons/<bible_books>", ExpositorySermonsView.as_view()),
    path("special-videos", SpecialVideosView.as_view()),
    path("new-believer-documents", NewBelieverDocumentsListView.as_view()),
    path("new-believer-documents/<slug>", NewBelieverDocumentsDetailsView.as_view()),
    path("soul-winning-lessons", SoulWinningLessonsListView.as_view()),
    path("soul-winning-lessons/<slug>", SoulWinningLessonsDetails.as_view()),
    path("discipleship-lessons", DiscipleshipLessonsListView.as_view()),
    path("discipleship-lessons/<slug>", DiscipleshipLessonsDetails.as_view()),
    path("discipler-class-lessons", DisciplerClassLessonsListView.as_view()),
    path("discipler-class-lessons/<slug>", DisciplerClassLessonsDetails.as_view()),
    path("biblical-theology-lessons", BiblicalTheologyLessonsListView.as_view()),
    path("biblical-theology-lessons/<slug>", BiblicalTheologyLessonsDetails.as_view()),
    path("missionary-letter", MissionaryLetterListView.as_view()),
    path("missionary-letter/<slug>", MissionaryLetterDetails.as_view()),
    path('contact-form', ContactFormView.as_view(), name='contact-form'),
    path('subscription/', views.subscribe, name='subscription'), 
]
