# Generated by Django 5.0.1 on 2024-05-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfaNewsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
